## This file is a template remove the .template to use the file

libraries:
  Movies:
    remove_overlays: false
    report_path: config/reports/Movies_Report.yml

    collection_files:
    - file: config/Movies_Collections.yml

    overlay_files:
    - pmm: resolution
      template_variables:
        horizontal_align: left
        vertical_align: top
        use_720p: false
        use_576p: false
        use_480p: false
        use_edition: false

    - pmm: ribbon

    - pmm: streaming
      template_variables:
        horizontal_align: center
        vertical_align: top
        vertical_offset: 15
        horizontal_offset: 0

    - pmm: ratings
      template_variables:
        rating1: critic
        rating1_image: imdb
        rating2: audience
        rating2_image: rt_tomato
        rating3: user
        rating3_image: tmdb
        horizontal_position: right

    - pmm: commonsense
      template_variables:
        horizontal_align: right
        vertical_align: top

    operations:
      mass_critic_rating_update: imdb
      mass_audience_rating_update: mdb_tomatoesaudience
      mass_user_rating_update: tmdb
      split_duplicates: true

  TV Shows:
    remove_overlays: false
    report_path: config/reports/Tv_Report.yml

    collection_files:
    - file: config/TV_Collections.yml

    overlay_files:
    - pmm: status
      schedule: weekly(sunday)
      template_variables:
        font: config/fonts/JetBrainsMonoNerdFont-Bold.ttf
        font_size: 60
        sync_mode: sync
        text_airing: A  I  R  I  N  G
        text_returning: R  E  T  U  R  N  I  N  G
        text_canceled: C  A  N  C  E  L  E  D
        text_ended: E  N  D  E  D
        horizontal_align: center
        horizontal_offset: 0
        vertical_offset: 0
        vertical_align: top
        back_color_airing: '#27C24C'
        back_color_returning: '#FFA500'
        back_color_canceled: '#ED1F1F'
        back_color_ended: '#6300EDFF'
        back_height: 85
        back_width: 1100

    - pmm: commonsense
      template_variables:
        horizontal_align: left
        vertical_align: bottom
        horizontal_offset: 11 # audience - 9
        vertical_offset: 13 # audience - 7
        font: config/fonts/JetBrainsMonoNerdFont-Bold.ttf
        font_size: 58

    - pmm: network
      template_variables:
        horizontal_align: center
        vertical_offset: 50
        vertical_align: bottom
        back_width: 621
        url: https://raw.githubusercontent.com/aedot/kometa-configf/main/overlays/images/network/shadow/<<key>>.png 
        back_color: 00 
   
    - pmm: ratings
      template_variables:
        rating1: critic
        rating1_image: imdb
        rating2: audience
        rating2_image: rt_tomato
        rating3: user
        rating3_image: tmdb
        horizontal_position: right
    operations:
      mass_critic_rating_update: imdb
      mass_audience_rating_update: mdb_tomatoesaudience
      mass_user_rating_update: tmdb
      mass_episode_critic_rating_update: imdb
      mass_episode_audience_rating_update: tmdb



settings:
  run_order:
  - operations
  - metadata
  - collections
  - overlays

  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  asset_depth: 0
  create_asset_folders: false
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: append
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_filtered: false
  show_options: false
  show_missing: true
  show_missing_assets: true
  save_report: false
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_user: all
  playlist_exclude_user:
  playlist_report: false
  verify_ssl: true
  custom_repo:
  check_nightly: false
  show_unconfigured: true
  playlist_exclude_users:
webhooks:                        # Can be individually specified per library as well
  error:
  version:
  run_start:
  run_end:
  changes:
  delete:
plex:                            # Can be individually specified per library as well; REQUIRED for the script to run
  url: http://192.168.10.11:32400
  token: ####################################
  timeout: 60
  clean_bundles:
  empty_trash: false
  optimize: false
  db_cache:
  verify_ssl:
tmdb:
  apikey: ####################################
  language: en
  cache_expiration: 60
  region:
tautulli:                        # Can be individually specified per library as well
  url: http://192.168.10.11:8181
  apikey: ####################################
omdb:
  apikey: d6eca8fa
  cache_expiration: 60
mdblist:
  apikey: ####################################
  cache_expiration: 60
# notifiarr:
#   apikey: ####################################
# anidb:                           # Not required for AniDB builders unless you want mature content
#   username: ######
#   password: ######
#   language: en
#   client:

Radarr:                          # Can be individually specified per library as well
  url: http://192.168.10.11:7878
  token: ####################################
  add_missing: false
  add_existing: false
  root_folder_path: /path/to/movies/directory
  monitor: true
  availability: announcedTV-s
  quality_profile: HD-1080p
  tag:
  search: false
  radarr_path:
  plex_path:

Sonarr:                          # Can be individually specified per library as well
  url: http://192.168.10.11:8989
  token: ####################################
  add_missing: false
  add_existing: false
  root_folder_path: /path/to/tvs/directory
  monitor: all
  quality_profile: HD-1080p
  language_profile: English
  series_type: standard
  season_folder: true
  tag:
  search: false
  cutoff_search: false
  sonarr_path:
  plex_path:

trakt:
  client_id: ####################################
  client_secret: ####################################
  pin: ####################################
  authorization:
    # everything below is autofilled by the script
    access_token:
    token_type:
    expires_in:
    refresh_token:
    scope:
    created_at:

# mal:
#   client_id: ####################
#   client_secret: ####################
#   authorization:
#     # everything below is autofilled by the script
#     access_token:
#     token_type:
#     expires_in:
#     refresh_token:
